# Generated by Django 5.1.1 on 2024-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
