# Generated by Django 5.1.1 on 2024-10-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
