# Generated by Django 5.1.1 on 2024-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
